const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const actions={app:'应用',renderer:'界面',connection:'服务连接',record:'记录',sync:'同步',handoff:'交接',distillation:'沉淀',update:'更新',feedback:'反馈发送'};
const phases={start:'开始',complete:'完成',failed:'失败',pending:'等待确认',selected:'已选择','open-requested':'已请求打开',preparing:'准备中',prepared:'已准备',opening:'正在打开'};
export function setupReportInbox(api,message) {
  const list=document.getElementById('reports-list'),detail=document.getElementById('report-detail'),filter=document.getElementById('reports-filter'),search=document.getElementById('reports-search');
  let items=[],selected=null,epoch=0;
  const path=item=>`problem-reports/${encodeURIComponent(item.subject)}/${encodeURIComponent(item.reportId)}`;
  function renderList() {
    const q=search.value.trim().toLowerCase();
    const visible=items.filter(item=>(!filter.value || item.state===filter.value) && (!q || [item.report.description,item.report.environment.version,item.subject,item.device,new Date(item.report.occurredAt).toLocaleString('zh-CN'),item.errorCodes?.join(' ')].join(' ').toLowerCase().includes(q)));
    list.innerHTML=visible.length ? visible.map((item,index)=>`<button class="report-inbox-row ${selected?.reportId===item.reportId && selected?.subject===item.subject ? 'active' : ''}" data-index="${items.indexOf(item)}"><strong>${esc(item.report.description.slice(0,55) || '截图反馈')}</strong><span class="badge">${esc(item.state)}</span><small>${esc(new Date(item.receivedAt).toLocaleString('zh-CN'))} · ${esc(item.report.environment.version)} · ${item.report.diagnostics ? '附诊断日志' : '未附日志'}</small></button>`).join('') : '<p>暂无匹配的反馈</p>';
  }
  async function select(item) {
    const current=epoch;
    const value=await api(path(item));if(current!==epoch)return;selected=value;
    const report=value.report;
    detail.hidden=false;detail.innerHTML=`<div class="section-heading"><h2>问题反馈</h2><select id="report-state" aria-label="处理状态">${['待排查','排查中','待补充','已解决'].map(state=>`<option ${value.state===state ? 'selected' : ''}>${state}</option>`).join('')}</select></div><p class="report-meta">${esc(value.reportId)} · ${esc(new Date(value.receivedAt).toLocaleString('zh-CN'))}<br>${esc(value.subject)} · 设备 ${esc(value.device)} · ${esc(report.environment.version)} / ${esc(report.environment.platform)} / ${esc(report.environment.arch)}</p><div class="report-evidence"><section><h3>用户描述与截图</h3><p class="report-description">${esc(report.description || '仅提交截图')}</p><div class="report-images">${report.screenshots.map(image=>`<a target="_blank" rel="noopener" href="/admin/api/${path(value)}/images/${image.id}"><img src="/admin/api/${path(value)}/images/${image.id}" alt="用户反馈截图"></a>`).join('')}</div></section><section><h3>程序记录的操作</h3>${report.diagnostics ? `<p class="report-meta">${esc(new Date(report.diagnostics.from).toLocaleString('zh-CN'))} — ${esc(new Date(report.diagnostics.to).toLocaleString('zh-CN'))}${report.diagnostics.truncated ? ' · 日志不完整' : ''}${report.diagnostics.previousExit ? ' · 上次未正常退出' : ''}</p><ol class="report-timeline">${report.diagnostics.events.map(event=>`<li><time>${esc(new Date(event.at).toLocaleTimeString('zh-CN'))}</time><div><strong>${actions[event.action]} · ${phases[event.phase]}</strong><small>${esc([event.executor,event.code,event.elapsedMs!==undefined ? `${event.elapsedMs} ms` : '',event.requestId ? `请求 ${event.requestId}` : ''].filter(Boolean).join(' · '))}</small></div></li>`).join('')}</ol>${value.requests?.length ? `<h3>关联后台请求</h3>${value.requests.map(request=>`<p class="report-meta">${esc(request.id)} · ${esc(request.operation)} · ${esc(request.status)}${request.error ? ` · ${esc(request.error)}` : ''}</p>`).join('')}` : ''}<details><summary>完整脱敏日志</summary><pre>${esc(JSON.stringify(report.diagnostics,null,2))}</pre></details>` : '<p>用户未附日志</p>'}</section></div><label>内部排查备注<textarea id="report-note" maxlength="4000">${esc(value.note)}</textarea><small>仅管理员可见</small></label><label>给用户的处理说明<textarea id="report-public-note" maxlength="4000">${esc(value.publicNote)}</textarea></label><div class="report-review-actions"><button id="delete-report">删除反馈</button><button id="save-report" class="primary">保存处理进展</button></div>`;
    detail.querySelector('#save-report').addEventListener('click',async event=>{event.currentTarget.disabled=true;try{await api(path(value),'PUT',{state:detail.querySelector('#report-state').value,note:detail.querySelector('#report-note').value,publicNote:detail.querySelector('#report-public-note').value});await refresh();await select(value);message('处理进展已保存');}catch(e){message(e.message,true);}finally{event.currentTarget.disabled=false;}});
    detail.querySelector('#delete-report').addEventListener('click',async()=>{if(!confirm('删除这份反馈及全部截图、日志和备注？删除后无法恢复。'))return;try{await api(path(value),'DELETE');selected=null;detail.replaceChildren();detail.hidden=true;await refresh();}catch(e){message(e.message,true);}});
    renderList();
  }
  async function refresh() {const current=epoch;const result=await api('problem-reports');if(current!==epoch)return;items=result.items;renderList();}
  list.addEventListener('click',event=>{const button=event.target.closest('[data-index]');if(button)void select(items[Number(button.dataset.index)]).catch(e=>message(e.message,true));});
  filter.addEventListener('change',renderList);search.addEventListener('input',renderList);
  document.getElementById('refresh-reports').addEventListener('click',()=>void refresh().catch(e=>message(e.message,true)));
  return {refresh,clear:()=>{epoch++;items=[];selected=null;list.replaceChildren();detail.replaceChildren();detail.hidden=true;}};
}
