export const RULES_PROMPT = `
RULE COORDINATION (required in the final content): Every item in deliverables, constraints, acceptanceCriteria and methods MUST include rule:{scope:"REUSABLE"|"INSTANCE"|"UNCERTAIN",status:"ACTIVE"|"PROPOSED"|"RETIRED",condition?:string,relation?:{kind:"DUPLICATE"|"SUPPLEMENTS"|"REPLACES"|"CONFLICT",target:"collection.key"}}. Purpose, inputs and materialRoles do not carry rule or document. Purpose describes the outcome only; never repeat constraints there. Preserve values, negation and applicability conditions. One-time details stay INSTANCE; unaccepted suggestions stay PROPOSED. UNCERTAIN means no evidence for a reusable scope. Repetition alone does not imply adoption.
Compare conversation AND adopted file rules: identical obligations under equal scope/conditions link DUPLICATE to one retained rule, preferably the normative document clause. New information is SUPPLEMENTS: its text contains only the new obligation, without repeating an already retained limit or instruction. For example a newly specified language should be a language requirement, not a second copy of the same length limit; preserve every genuinely new value and condition. Explicit enduring correction is REPLACES (same scope AND condition), ambiguous contradiction is CONFLICT with a blocking issue. No cycles, mutual deletion, arbitrary priority by filename, or latest-message-wins across works. Repeated acceptance criteria may reference a retained constraint via DUPLICATE; no need to restate each constraint as a separate criterion unless it adds a check. Preserve adoption changes even if wording repeats. Existing reusable rules cannot be overwritten by an INSTANCE exception.
Definition inputs are REUSABLE ROLE SPECIFICATIONS, not a place to store instance values. A fresh task-specific value (script, research question, change request) establishes or fills its generic input role; describe the role without that historical value in key, text, choices or default. Keep historical values only in source evidence. A user saying "next time I only provide a new X" specifies input ROLE X; do not discard that role as a one-time requirement or interpret "no extra mandatory inputs" as removing X. Keep the old value out of defaults AND input labels. If "topic" already represents a role, never add a second "current_topic" input to hold the original topic. One reusable role appears once.
Instructions about extraction ("do not make this temporary tool mandatory", "do not turn skill internals into my constraints") govern what Worket retains; they are not task deliverables or execution constraints. Excluding a one-off choice means omitting that enduring obligation, not manufacturing a permanent prohibition on using the tool. Preserve a genuinely explicit execution prohibition ("never use X in reports") as a rule. Do not confuse that prohibition with a request not to generalize an instance.
The exact rule Item nesting is {key,text,basis,rule,document?}. document is a SIBLING of basis and rule, NEVER inside basis. Before returning, check all DOCUMENT_STATED items have document at item.document.
Files have document.role set by the user. Only file.content with role NORMATIVE may supply a normative clause. REFERENCE and INPUT are not adopted specifications. File metadata never proves content or coverage. Every document-derived rule MUST carry document:{source:{snapshotId:"wire",workId:"source key",eventId:"file key"},hash:"exact event hash",name:"provided file name",startLine:1,endLine:1}. Lines are one-based inclusive in the original file content split on newline. Select an atomic clause, preserving scope and exceptions in rule.condition or selecting necessary context. Text MUST equal the selected lines verbatim. Its basis is SOURCE with origin DOCUMENT_STATED and refs including the file; optionally retain related conversation refs. Never put DOCUMENT_STATED on a non-rule item.
The normative files referenced this way are automatically pinned; do NOT request a second materialRoles binding or an additional blanket 'follow the whole file' rule, which would reactivate overridden/unselected clauses. Non-text assets can still use materialRoles. File names are not placeholders for actual requirements. Extract all supported applicable requirements, including unique supplements from dialogue. Do not add generic quality requirements absent from the sources.
For COMPATIBLE results, groups may be []; if present groups.sourceKeys contains source keys such as work-1, NOT work-1/event-1. Return all processed keys in coverage regardless of whether they yield reusable requirements. Never include the evaluation criteria as facts.
In the final coverage object, exclusions MUST be an empty array []. Every supplied event must be processed exactly once and appear in eventKeys, including task inputs, repeated statements, one-time details and unaccepted suggestions. An event that yields no reusable requirement is still processed; represent this with no rule change or an INSTANCE/PROPOSED item as appropriate, NEVER by listing it as an excluded event.`;
